name = "Baboon"
grammar = "baboon"
path_suffixes = ["baboon", "bmo"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 2

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

autoclose_before = ";:.,=}])>"
